-- 코드를 입력하세요
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE 
WHERE SUBSTR(SALES_DATE,7,1) = 3

UNION ALL

SELECT SALES_DATE, PRODUCT_ID, NULL AS 'USER_ID', SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SUBSTR(SALES_DATE,7,1) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
;